name: Daily commit

on:
  schedule:
    - cron: '0 1 * * *'  # Daily at 01:00 UTC
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
          fetch-depth: 0  # ⚠️ Needed for rebase to work!

      - name: Setup Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Pull latest main branch
        run: |
          git pull --rebase origin main || {
            echo "❌ Git pull failed"
            exit 1
          }

      - name: Update timestamp file
        run: |
          echo "Last automatic commit: $(date -u +'%Y-%m-%dT%H:%M:%SZ')" > last_commit.txt

      - name: Commit and push if changed
        run: |
          git add last_commit.txt
          if git diff --cached --quiet; then
            echo "✅ No changes to commit"
            exit 0
          fi

          git commit -m "chore: daily commit $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          git push origin main
