permissions:
  contents: write

name: Daily commit

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Git identity
        run: |
          git config --global user.name "Kartikeya Sharma"
          git config --global user.email "kartikrb1.0@gmail.com"

      - name: Update timestamp
        run: |
          echo "Last automatic commit: $(date -u +'%Y-%m-%dT%H:%M:%SZ')" > last_commit.txt

      - name: Commit and push
        run: |
          git add last_commit.txt
          git commit -m "Daily commit $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || exit 0
          git push
